#================================================
# vim/rc/core.toml
#
# Core plugins
#================================================
[[plugins]]
repo   = 'Shougo/dein.vim'
frozen = 1

[[plugins]]
repo      = 'Shougo/context_filetype.vim'
on_source = ['neosnippet.vim', 'vim-precious']
hook_add  = '''
  let g:context_filetype#filetypes = get(g:, 'context_filetype#filetypes', {})
  let g:context_filetype#filetypes.toml = [
      \   {
      \     'filetype': 'vim',
      \     'start': '^\s*hook_\(add\|source\|post_source\)\s*=\s*'."'"."''",
      \     'end': "'"."''"
      \   },
      \   {
      \     'filetype': 'vim',
      \     'start': '^\s*hook_\(add\|source\|post_source\)\s*=\s*'.'"""',
      \     'end': '"""'
      \   }
      \ ]
'''

[[plugins]]
repo = 'prabirshrestha/async.vim'

# for Vim8
# [[plugins]]
# repo = 'roxma/nvim-yarp'
# if   = 'vimrc#is_vim8()'

# [[plugins]]
# repo = 'roxma/vim-hug-neovim-rpc'
# if   = 'vimrc#is_vim8()'
# vim:ft=toml:ts=2:sw=2:fdm=marker
