## FZF
[[plugins]]
repo      = '$FZF_HOME'
if        = 'exists("$FZF_HOME") && executable("fzf")'
on_source = ['fzf.vim']

[[plugins]]
repo     = 'junegunn/fzf.vim'
if       = 'executable("fzf")'
on_func  = 'fzf#'
on_event = ['VimEnter']
hook_add = '''
  source $VIMDIR/rc/fzf.vim

  if vimrc#is_nvim()
    autocmd MyCmdGroup TermOpen * tnoremap <Esc> <C-\><C-n>
  else
    autocmd MyCmdGroup TerminalOpen * tnoremap <Esc> <C-\><C-n>
  endif
  autocmd MyCmdGroup FileType fzf tunmap <Esc>
'''

## filetree
[[plugins]]
repo     = 'lambdalisue/fern.vim'
on_cmd   = ['Fern']
# vim:ft=toml:ts=2:sw=2:fdm=marker:et
