#================================================
# vim/rc/fzf.toml
#================================================
[[plugins]]
repo      = '$FZF_HOME'
on_source = ['fzf.vim']

[[plugins]]
repo     = 'junegunn/fzf.vim'
on_func  = 'fzf#'
on_event = ['VimEnter']
hook_post_source = '''
  let g:fzf_layout = {'down': '~30%'}
  let g:fzf_action = {
      \ 'ctrl-s': 'split',
      \ 'ctrl-v': 'vsplit'
      \}

  call plugins#fzf#commands()
  call plugins#fzf#mapping()
'''
# vim:ft=toml:ts=2:sw=2:fdm=marker:et
