#================================================
# vim/rc/git.toml
#
# Plugins for Git
#================================================
[[plugins]]
repo        = 'lambdalisue/gina.vim'
on_cmd      = ['Gina']
on_func     = 'gina#'
hook_add    = '''
  command! -nargs=* Git Gina <q-args>
  autocmd MyCmdGroup FileType gina-commit execute "normal! G"
'''
hook_source = '''
  for kind in ['log', 'status', 'diff']
    call gina#custom#command#option(kind, '--opener', 'split')
    execute 'autocmd' 'MyCmdGroup Filetype gine-' . kind . ' nnoremap q :q<CR>'
  endfor

  cabbrev git Gina
'''

[[plugins]]
repo        = 'airblade/vim-gitgutter'
on_event    = ['BufWinEnter']
hook_source = '''
  let g:gitgutter_async   = 1
  let g:gitgutter_highlight_lines = 0

  let g:gitgutter_sign_added    = '+'
  let g:gitgutter_sign_modified = '*'
  let g:gitgutter_sign_removed  = '-'
  let g:gitgutter_sign_modified_removed = '*'

  noremap [git] <Nop>
  map <C-g> [git]
  nmap <silent> [git]h :GitGutterLineHighlightsToggle<CR>
  nmap <silent> [git]n :GitGutterNextHunk<CR>
  nmap <silent> [git]p :GitGutterPrevHunk<CR>
'''

# For FZF
[[plugins]]
repo   = 'tpope/vim-fugitive'
on_cmd = ['FugitiveFind']
# vim:ft=toml:ts=2:sw=2:fdm=marker
