#================================================
# vim/rc/lsp.toml
#================================================
[[plugins]]
repo        = 'prabirshrestha/vim-lsp'
depends     = ['async.vim']
hook_add    = '''
  call plugins#lsp#register_lsp()
'''
hook_source = '''
  let g:lsp_signs_enabled = 1
  let g:lsp_diagnostics_echo_cursor = 1

  let g:lsp_signs_error = {'text': '✗'}
  let g:lsp_signs_warning = {'text': '!'}
'''

[[plugins]]
repo     = 'prabirshrestha/asyncomplete-lsp.vim'
depends  = ['asyncomplete.vim', 'vim-lsp']
# vim:ft=toml:ts=2:sw=2:fdm=marker:et
