"==========================================================
" vim/vimrc
"
" Author: Yasumasa TAMURA (tamura.yasumasa@gmail.com)
" Last Change: 29 Mar. 2018.
"==========================================================
if 1
  if &compatible | set nocompatible | endif
  execute 'source' fnamemodify(expand('<sfile>'), ':h:p') . '/init.vim'
endif
" vim:ft=vim:ts=2:sw=2:fdm=marker
