# [language.cpp]  # obsolete
# command = "cquery"
# args = ["--init={\"cacheDirectory\": \"${project_root}/.cquery_cache\"}"]

[language.cpp]
command = "ccls"
args = ["--init={\"cacheDirectory\": \"${project_root}/.ccls_cache\"}"]

# [language.rust]
# command = "rls"
# install = [
#   ["rustup", "update"],
#   ["rustup", "component", "add", "rls-preview", "rust-analysis", "rust-src"],
# ]

# [language.javascript]
# command = "flow"
# args = ["lsp"]
# install = [["npm", "install", "-g", "flow-bin"]]

# [language.html]
# command = "html-languageserver"
# args = ["--stdio"]
# install = [["npm", "install", "-g", "vscode-html-languageserver-bin"]]

# [language.ocaml]
# command = "ocaml-language-server"
# args = ["--stdio"]
# install = [["npm", "install", "-g", "ocaml-language-server"]]

# [language.python]
# command = "pyls"
# install = [["pip", "install", "python-language-server"]]

# [language.haskell]
# command = "hie"
# args = ["--lsp"]

# [language.go]
# command = "go-langserver"
# args = ["-mode", "stdio", "-gocodecompletion"]
# install = [["go", "get", "-u", "github.com/sourcegraph/go-langserver"]]

# [language.dart]
# command = "dart_language_server"
# install = [["pub", "global", "activate", "dart_language_server"]]

# [language.ruby]
# command = "solargraph"
# args = ["stdio"]
# install = [["gem", "install", "solargraph"]]
