[[plugins]]
repo    = 'Shougo/dein.vim'

[[plugins]]
repo    = 'Shougo/vimproc'
build   = 'make'

[[plugins]]
repo    = 'Shougo/context_filetype.vim'

[[plugins]]
repo    = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo    = 'Shougo/unite-sudo'

[[plugins]]
repo    = 'godlygeek/csapprox'
if      = "!has('gui_running') || has('nvim')"

[[plugins]]
repo    = 'itchyny/lightline.vim'

[[plugins]]
repo    = 'tamy0612/template.vim'

[[plugins]]
repo    = 'tamy0612/argos.vim'

[[plugins]]
repo    = 'fuenor/qfixgrep'

[[plugins]]
repo    = 'tpope/vim-fugitive'
