# Create XDG base directories unless exist
for dir in $XDG_CONFIG_HOME $XDG_CACHE_HOME $XDG_DATA_HOME
do
    [[ -d $dir ]] || mkdir -p $dir
done

# auto compile
if [ ! -f $HOME/.zshenv.zwc -o $HOME/.zshenv -nt $HOME/.zshenv.zwc ]; then
  zcompile $HOME/.zshenv
fi