#================================================
# vim/rc/filetype/cpp.toml
#================================================
[[plugins]]
repo = 'vim-jp/cpp-vim'

[[plugins]]
repo = 'octol/vim-cpp-enhanced-highlight'

[[plugins]]
repo        = 'keremc/asyncomplete-clang.vim'
depends     = ['asyncomplete.vim']
hook_source = '''
  autocmd MyCmdGroup User asyncomplete_setup call asyncomplete#register_source(
      \ asyncomplete#sources#clang#get_source_options({
      \     'priority': 10,
      \     'config': {
      \         'clang_path': '/opt/llvm/bin/clang',
      \         'clang_args': {
      \             'default': ['-I/opt/llvm/include'],
      \             'cpp': ['-std=c++1z', '-I/opt/llvm/include']
      \         }
      \     }
      \ }))
'''

[[plugins]]
repo = 'kyouryuukunn/asyncomplete-neoinclude.vim'
depends = ['asyncomplete.vim']
hook_source = '''
  autocmd MyCmdGroup User asyncomplete_setup call asyncomplete#register_source(asyncomplete#sources#neoinclude#get_source_options({
      \ 'name': 'neoinclude',
      \ 'whitelist': ['c', 'cpp'],
      \ 'reflesh_pattern': '\(<|"\|/\)$',
      \ 'completor': function('asyncomplete#sources#neoinclude#completor')
      \}))
'''

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_func = 'neoinclude#'

# vim:ft=toml:ts=2:sw=2:fdm=marker:et
