#================================================
# vim/rc/filetype/toml.toml
#================================================
[[plugins]]
repo      = 'cespare/vim-toml'
hook_add  = '''
  autocmd MyCmdGroup BufNewFile,BufRead *.toml set filetype=toml
'''
# vim:ft=toml:ts=2:sw=2:fdm=marker
