#================================================
# vim/rc/filetype/typescript.toml
#================================================
[[plugins]]
repo = 'leafgarland/typescript-vim'
hook_add = '''
  autocmd! BufNewFile,BufRead *.ts  set filetype=typescript
  autocmd! BufNewFile,BufRead *.tsx set filetype=typescript
'''
hook_source = '''
  set tabstop=2
  set shiftwidth=2
'''
# vim:ft=toml:ts=2:sw=2:fdm=marker:et
