#================================================
# vim/rc/filetype/vim.toml
#
# Plugins for Vim script
#================================================
# Completion
[[plugins]]
repo = 'prabirshrestha/asyncomplete-necovim.vim'
depends = ['asyncomplete.vim']
hook_source = '''
  call asyncomplete#register_source(asyncomplete#sources#necovim#get_source_options({
      \ 'name': 'necovim',
      \ 'whitelist': ['vim'],
      \ 'priority': 5,
      \ 'completor': function('asyncomplete#sources#necovim#completor'),
      \ }))
'''

[[plugins]]
repo    = 'Shougo/neco-vim'
on_func = ['necovim#']


# Linter
[[plugins]]
repo      = 'ynkdir/vim-vimlparser'
on_source = ['vim-vimlint']

[[plugins]]
repo      = 'syngan/vim-vimlint'
depends   = ['vim-vimlparser']
on_func   = 'vimlint#vimlint'
# vim:ft=toml:ts=2:sw=2:fdm=marker:et
